### PR TITLE
Whiptail

### PR DESCRIPTION
**Pull request by dingyifei**

### CODE REVIEW

**Comment by dingyifei** [comment]
I don't know what's going on... it seems like I'm refactoring and changing things all over the place to make the functions work with whiptail.

**Comment by th33xitus** [comment]
> I don't know what's going on... it seems like I'm refactoring and changing things all over the place to make the functions work with whiptail.

😂 i see that. the thing is, i don't have any experiences with whiptail yet so i guess i just let you do your thing and see where it goes. i will try to check out this PR soon to have a look on how it all came together.

**Comment by dingyifei** [comment]
https://drive.google.com/file/d/1Hl8Kyf70odNpOkEbrCtMHAEGZYcrq7yx/view?usp=sharing

This is what I'm currently getting, there are some bugs here and there because the main_menu was called at some places, I was able to complete Klipper installation yesterday but my wifi is shitty rn...

**Comment by dingyifei** [comment]
Borked dingyifei/whiptail so i'm using the whiptail-fix branch now... #141 I successfully encountered some interesting git bugs
```
remote: Resolving deltas: 100% (5/5), completed with 4 local objects.
remote: fatal: did not receive expected object ad2b812c6fa662d5fced3840983629bb3148eca5
remote: fatal error in commit_refs
To https://github.com/dingyifei/kiauh.git
 ! [remote rejected] whiptail -> whiptail (failure)
error: failed to push some refs to 'https://github.com/dingyifei/kiauh.git'
```

**Comment by dingyifei** [comment]
I think my local repo is broken or I had too many changes that aren't committed

**Pull request closed without merging**
