### PR TITLE
feat: add Mobileraker

### PR DESCRIPTION
**Pull request by Clon1998**
I thought I will join the party and also add Mobileraker to Kiauh.
I manually tested install, removal, and update!
Let me know if there is something wrong or missing!

### CODE REVIEW

**Comment by Clon1998** [comment]
Bump @th33xitus

**Comment by th33xitus** [comment]
Hey, thanks for the PR, i will soon review, test and want to merge it. Sorry i haven't replied earlier.

**Comment by th33xitus** [comment]
Hi! So i had a look at the PR and it looks good to me.
Two things i had to do though, i had to fix the `patch_mobileraker_update_manager` function as the global variable `KLIPPER_CONFIG` is deprecated and not used anymore. Now the function works properly again. I also went ahead and solved a merge conflict by merging the current master into this PR.

Thanks for your contribution! I hope to get your future support in case anything Mobileraker has to be resolved :)

**Comment by Clon1998** [comment]
Thanks for your work!

**Pull request merged**
